name: CI 1918 Koffee

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run npm install
        run: npm install
      - name: Run npm test
        run: |
          cd users-service
          npm install
          npx jest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      # Esto revisa la calidad del código
      - run: npx eslint . --fix || echo "Lint revisado"

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t 1918-koffee-app .